# Postgre baasist andmete importimine

In [1]:
!pip3 install psycopg2-binary

Defaulting to user installation because normal site-packages is not writeable
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp39-cp39-macosx_11_0_arm64.whl (3.9 MB)
     |████████████████████████████████| 3.9 MB 3.0 MB/s eta 0:00:01
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11
WARNING: You are using pip version 21.2.4; however, version 26.0.1 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.

In [8]:
!pip3 install sqlalchemy

Defaulting to user installation because normal site-packages is not writeable
Collecting sqlalchemy
  Downloading sqlalchemy-2.0.49-cp39-cp39-macosx_11_0_arm64.whl (2.2 MB)
     |████████████████████████████████| 2.2 MB 2.9 MB/s eta 0:00:01
Requirement already satisfied: typing-extensions>=4.6.0 in /Users/erinvainsalu/Library/Python/3.9/lib/python/site-packages (from sqlalchemy) (4.15.0)
Installing collected packages: sqlalchemy
Successfully installed sqlalchemy-2.0.49
WARNING: You are using pip version 21.2.4; however, version 26.0.1 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.

In [7]:
import pandas as pd
import psycopg2

from sqlalchemy import create_engine

In [12]:
conn = psycopg2.connect(
    host='localhost',
    database='cafe',
    user='erinvainsalu'
)

In [ ]:
df = pd.read_sql("SELECT * FROM cafe.cafe_sales_cleaned", conn)
conn.close()

/var/folders/rf/7fksn3z54135z8xtsc66dws00000gn/T/ipykernel_75714/458908448.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql("SELECT * FROM sales.sales_table", conn)

In [17]:
engine = create_engine("postgresql://erinvainsalu@localhost:5432/andmetarkus")
df = pd.read_sql("SELECT * FROM sales.sales_table", engine)
df

,sale_id,date,customer_id,product_id,quantity,unit_price,discount,sales_rep_id,region_id,sales_sum
0,S00034,2023-08-30,C001,P002,9,44.44,0.05,SR03,R02,379.962
1,S00035,2020-01-22,C002,P004,2,96.12,0.00,SR02,R02,192.240
2,S00036,2020-09-09,C001,P004,6,35.94,0.15,SR01,R01,183.294
3,S00037,2022-01-17,C002,P004,3,15.66,0.10,SR02,R02,42.282
4,S00038,2022-05-06,C003,P001,5,44.63,0.10,SR03,R01,200.835
...,...,...,...,...,...,...,...,...,...,...
11764,S11994,2025-04-23,C004,P004,8,69.45,0.15,SR01,R01,472.260
11765,S11995,2025-05-06,C004,P004,7,90.08,0.15,SR01,R03,535.976
11766,S11997,2025-08-29,C002,P002,6,33.93,0.05,SR01,R03,193.401
11767,S11998,2025-05-18,C003,P001,8,55.70,0.15,SR01,R01,378.760
11768,S12000,2025-08-26,C003,P002,5,22.18,0.05,SR03,R02,105.355

# Andmete lugemine veebi APIst JSON kujul

In [18]:
!pip3 install requests

Defaulting to user installation because normal site-packages is not writeable
Collecting requests
  Downloading requests-2.32.5-py3-none-any.whl (64 kB)
     |████████████████████████████████| 64 kB 1.4 MB/s eta 0:00:01
Collecting urllib3<3,>=1.21.1
  Downloading urllib3-2.6.3-py3-none-any.whl (131 kB)
     |████████████████████████████████| 131 kB 2.1 MB/s eta 0:00:01
Collecting idna<4,>=2.5
  Downloading idna-3.11-py3-none-any.whl (71 kB)
     |████████████████████████████████| 71 kB 3.6 MB/s eta 0:00:01
Collecting certifi>=2017.4.17
  Downloading certifi-2026.2.25-py3-none-any.whl (153 kB)
     |████████████████████████████████| 153 kB 3.3 MB/s eta 0:00:01
Collecting charset_normalizer<4,>=2
  Downloading charset_normalizer-3.4.7-cp39-cp39-macosx_10_9_universal2.whl (299 kB)
     |████████████████████████████████| 299 kB 3.0 MB/s eta 0:00:01
Installing collected packages: urllib3, idna, charset-normalizer, certifi, requests
Successfully installed certifi-2026.2.25 charset-normalizer-3.4.7 idna-3.11 requests-2.32.5 urllib3-2.6.3
WARNING: You are using pip version 21.2.4; however, version 26.0.1 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.

In [2]:
import requests

/Users/erinvainsalu/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

In [ ]:
response = requests.get("https://jsonplaceholder.typicode.com/posts")
response.json()[:3]

[{'userId': 1,
  'id': 1,
  'title': 'sunt aut facere repellat provident occaecati excepturi optio reprehenderit',
  'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'},
 {'userId': 1,
  'id': 2,
  'title': 'qui est esse',
  'body': 'est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla'},
 {'userId': 1,
  'id': 3,
  'title': 'ea molestias quasi exercitationem repellat qui ipsa sit aut',
  'body': 'et iusto sed quo iure\nvoluptatem occaecati omnis eligendi aut ad\nvoluptatem doloribus vel accusantium quis pariatur\nmolestiae porro eius odio et labore et velit aut'}]

In [8]:
df = pd.DataFrame(response.json())
df

,userId,id,title,body
0,1,1,sunt aut facere repellat provident occaecati e...,quia et suscipit\nsuscipit recusandae consequu...
1,1,2,qui est esse,est rerum tempore vitae\nsequi sint nihil repr...
2,1,3,ea molestias quasi exercitationem repellat qui...,et iusto sed quo iure\nvoluptatem occaecati om...
3,1,4,eum et est occaecati,ullam et saepe reiciendis voluptatem adipisci\...
4,1,5,nesciunt quas odio,repudiandae veniam quaerat sunt sed\nalias aut...
...,...,...,...,...
95,10,96,quaerat velit veniam amet cupiditate aut numqu...,in non odio excepturi sint eum\nlabore volupta...
96,10,97,quas fugiat ut perspiciatis vero provident,eum non blanditiis soluta porro quibusdam volu...
97,10,98,laboriosam dolor voluptates,doloremque ex facilis sit sint culpa\nsoluta a...
98,10,99,temporibus sit alias delectus eligendi possimu...,quo deleniti praesentium dicta non quod\naut e...
99,10,100,at nam consequatur ea labore ea harum,cupiditate quo est a modi nesciunt soluta\nips...

# Vigade haldus

In [10]:
try:
    conn = psycopg2.connect(
    host='localhost',
    database='mydb',
    user='kasutaja'
    )
    df = pd.read_sql("SELECT * FROM cafe.cafe_sales_cleaned", conn)
    conn.close()
except:
    print("Viga!")

Viga!

In [14]:
countries = ["Estonia", "Latvia", "Lithuania"]

try:
    fourth_country = countries[3]
    print(fourth_country)
except IndexError: # IndexError ütleb mis tüüpi viga kinni püüda
    print("4ndat riiki pole")

4ndat riiki pole

In [22]:
def numeric_year(year_string: str) -> int:
    year_number_components = year_string.split(" ")
    year_number_str = year_number_components[0]
    year_era_notation_str = year_number_components[1]
    if year_era_notation_str == "A.D.":
        return int(year_number_str)
    if year_era_notation_str == "B.C.":
        return -int(year_number_str)
    raise ValueError(f"{year_string} does not seem to be a valid year number")
    

print(numeric_year("2024 A.D.")) #2024
print(numeric_year("1 B.C.")) #-1
print(numeric_year("1 BC.")) #-1

2024
-1

ValueError: 1 BC. does not seem to be a valid year number