# Python, päev 1
Pythoni baasteadmised.
## *Hello, world*

In [50]:
print('Hello, World!')

Hello, World!

In [51]:
"Hello, World!"

'Hello, World!'

# Andmetüübid

In [52]:
PI = 3.14159 # float ehk ujukomaarv
aasta = 2026 # int ehk täisarv
sun_rises_from_est = True # bool ehk tõeväärtus, võib olla True või False, alati suure algustähega
# suured algustähed on konventsioon, mis näitab, et tegemist on konstantiga, mida ei tohiks muuta.

In [53]:
years = [2020, 2021, 2022, 2023, 2024, 2025, 2026] # List ehk järjend, mis võib sisaldada erinevat tüüpi elemente. Järjekord on oluline, saab küsida elemente indeksiga, mis algab 0-st.
person = {
    "name": "Alice", 
    "age": 30, 
    "city": "New York"
    } # Dict ehk sõnastik, mis koosneb võtme-väärtuse paaridest, muutuv ja järjestamata.

fruits = {"apples", "oranges", "bananas"} # Set ehk hulk, mis on muutumatu ja järjestamata kogum unikaalseid elemente. Kogum ei saa sisaldada duplikaate.
tuple_example = (1, 2, 3) # Tuple ehk ennik, mis on muutumatu. Järjestatud ja muutumatu kogum elemente.

# Funktsioonid

In [54]:
'''
Siin vahel olev docstring. Kui küsida funktsiooni kirjeldust ?greet - prinditakse välja ka see "kommentaar".
'''
def greet(name: str, time_of_day: str = "day") -> None:
    # Argumendid, millel on vaikeväärtus, peavad olema funktsioonis pärast neid argumente, millel ei ole vaikeväärtust.
    print(f"Good {time_of_day}, {name}!") # f loob võimaluse kasutada stringi sees muutujate väärtusi, mis on mugavam kui stringi concatenation. f ütleb, et stringi sees looksulgused olev on muutuja.

print("This is outside the function.")

This is outside the function.

In [55]:
number = 42
f"Number is {number}"

'Number is 42'

In [56]:
greet("Tiina", "morning")
greet("Tiina")
greet(name="Tiina",time_of_day="evening")
greet(time_of_day="evening", name="Tiina")

Good morning, Tiina!
Good day, Tiina!
Good evening, Tiina!
Good evening, Tiina!

Funktsiooni kohta info küsimine

In [57]:
?print

Docstring:
print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

Prints the values to a stream, or to sys.stdout by default.
Optional keyword arguments:
file:  a file-like object (stream); defaults to the current sys.stdout.
sep:   string inserted between values, default a space.
end:   string appended after the last value, default a newline.
flush: whether to forcibly flush the stream.
Type:      builtin_function_or_method

In [58]:
def add(a: int, b: int) -> int: # -> int näitab, et funktsioon peaks tagastama int tüüpi väärtuse. -> None ütleb, et funktsioon ei tagasta midagi.
    return a + b

In [59]:
add(5, 7)

12

## if/else

In [60]:
def make_sense_of_this_year(year: int):
    if year < 0:
        print("B.C.")
        if year <= -10000:
            print("Stone age...")
    elif year == 0:
        print("Happy birthday, Jesus!")
    elif year == 1978:
        print("Happy birthday, Mati!")
    else:
        print("A.D.")

make_sense_of_this_year(-90)

B.C.

In [61]:
def make_sense_of_this_year_v2(year: int) -> str:
    if year < 0:
        tekst = "B.C."
        if year <= -10000:
            tekst = "Stone age..."
    elif year == 0:
        tekst = "Happy birthday, Jesus!"
    elif year == 1978:
        tekst = "Happy birthday, Mati!"
    else:
        tekst = "A.D."
    return tekst

make_sense_of_this_year_v2(-10000)

'Stone age...'

In [ ]:
def print_year(year: int):
    if year < 0:
        print(f"{abs(year)} B.C.")
    else:
        print(f"{year} A.D.")

print_year(-90)
print_year(2025)

In [63]:
def print_year(year: int) -> str:
    if year < 0:
        return f"{abs(year)} B.C."
    else:
        return f"{year} A.D."

print(print_year(-90))
print(print_year(2025))

90 B.C.
2025 A.D.

In [48]:
# False or True
# False and True
2025 < 0 or True

True

In [64]:
print("Filmi nimi on 'Matrix'")
print('Filmi nimi on "Matrix"')

Filmi nimi on 'Matrix'
Filmi nimi on "Matrix"

# For loop

In [65]:
for i in range(5):
    print("Hello, world")

Hello, world
Hello, world
Hello, world
Hello, world
Hello, world

In [75]:
years = [2021, 2022, 2023, 2024, 2025]

for year in years:
    print(f"Happy start of {year}")

for year in years:
    print(f"Happy start of {year}")
    if year > 2023:
        break

Happy start of 2021
Happy start of 2022
Happy start of 2023
Happy start of 2024
Happy start of 2025
Happy start of 2021
Happy start of 2022
Happy start of 2023
Happy start of 2024

In [74]:
for year in years[:3]:
    print(f"Happy start of {year}")

print(years[0])
print(years[0:3])
print(years[:3])
print(years[3:])
print(years[0:3:2])

Happy start of 2021
Happy start of 2022
Happy start of 2023
2021
[2021, 2022, 2023]
[2021, 2022, 2023]
[2024, 2025]
[2021, 2023]

# Pandas

In [ ]:
!pip3 install pandas # ! ütleb, et tegemist ei ole pythoni koodiga, vaid näiteks tavalise käsurea käsuga

Defaulting to user installation because normal site-packages is not writeable
Collecting pandas
  Downloading pandas-2.3.3-cp39-cp39-macosx_11_0_arm64.whl (10.8 MB)
     |████████████████████████████████| 10.8 MB 1.3 MB/s eta 0:00:01
Collecting pytz>=2020.1
  Downloading pytz-2026.1.post1-py2.py3-none-any.whl (510 kB)
     |████████████████████████████████| 510 kB 1.1 MB/s eta 0:00:01
Collecting numpy>=1.22.4
  Downloading numpy-2.0.2-cp39-cp39-macosx_14_0_arm64.whl (5.3 MB)
     |████████████████████████████████| 5.3 MB 1.1 MB/s eta 0:00:01
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/erinvainsalu/Library/Python/3.9/lib/python/site-packages (from pandas) (2.9.0.post0)
Collecting tzdata>=2022.7
  Downloading tzdata-2026.1-py2.py3-none-any.whl (348 kB)
     |████████████████████████████████| 348 kB 1.1 MB/s eta 0:00:01
Requirement already satisfied: six>=1.5 in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas) (1.15.0)
Installing collected packages: tzdata, pytz, numpy, pandas
Successfully installed numpy-2.0.2 pandas-2.3.3 pytz-2026.1.post1 tzdata-2026.1
WARNING: You are using pip version 21.2.4; however, version 26.0.1 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.

In [79]:
import pandas as pd

In [85]:
data = pd.DataFrame({
    "name": ["Alice", "Bob", "Charlie"],
    "age": [30, 25, 35],
    "city": ["New York", "Los Angeles", "Chicago"]
})
data
# data.name[0]

      name  age         city
0    Alice   30     New York
1      Bob   25  Los Angeles
2  Charlie   35      Chicago

In [ ]:
# dataframe'i CSV faili kirjutamine
data.to_csv("not_very_sensible_data.csv",index=False)

In [87]:
people = pd.read_csv("not_very_sensible_data.csv")
people

      name  age         city
0    Alice   30     New York
1      Bob   25  Los Angeles
2  Charlie   35      Chicago

In [89]:
people[["name", "age"]]

      name  age
0    Alice   30
1      Bob   25
2  Charlie   35

# DuckDB

In [90]:
!pip3 install duckdb # ! ütleb, et tegemist ei ole pythoni koodiga, vaid näiteks tavalise käsurea käsuga

Defaulting to user installation because normal site-packages is not writeable
Collecting duckdb
  Downloading duckdb-1.4.4-cp39-cp39-macosx_11_0_arm64.whl (13.7 MB)
     |████████████████████████████████| 13.7 MB 1.3 MB/s eta 0:00:01
Installing collected packages: duckdb
Successfully installed duckdb-1.4.4
WARNING: You are using pip version 21.2.4; however, version 26.0.1 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.

In [92]:
!pip3 install scikit-learn

Defaulting to user installation because normal site-packages is not writeable
Collecting scikit-learn
  Downloading scikit_learn-1.6.1-cp39-cp39-macosx_12_0_arm64.whl (11.1 MB)
     |████████████████████████████████| 11.1 MB 3.4 MB/s eta 0:00:01
Collecting joblib>=1.2.0
  Downloading joblib-1.5.3-py3-none-any.whl (309 kB)
     |████████████████████████████████| 309 kB 4.3 MB/s eta 0:00:01
Requirement already satisfied: numpy>=1.19.5 in /Users/erinvainsalu/Library/Python/3.9/lib/python/site-packages (from scikit-learn) (2.0.2)
Collecting threadpoolctl>=3.1.0
  Downloading threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Collecting scipy>=1.6.0
  Downloading scipy-1.13.1-cp39-cp39-macosx_12_0_arm64.whl (30.3 MB)
     |████████████████████████████████| 30.3 MB 539 kB/s eta 0:00:01
Installing collected packages: threadpoolctl, scipy, joblib, scikit-learn
Successfully installed joblib-1.5.3 scikit-learn-1.6.1 scipy-1.13.1 threadpoolctl-3.6.0
WARNING: You are using pip version 21.2.4; however, version 26.0.1 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.

In [91]:
import duckdb

In [ ]:
from sklearn.datasets import load_iris
import pandas as pd

iris_data = load_iris()
iris = pd.DataFrame(iris_data.data, columns=iris_data.feature_names)
iris['target'] = iris_data.target
iris['species'] = iris['target'].map(dict(enumerate(iris_data.target_names)))
iris.pop('target')
# rename funktsioon tagastab uue tabeli
iris = iris.rename(columns={
    "sepal length (cm)": "sepal_length",
    "sepal width (cm)": "sepal_width",
    "petal length (cm)": "petal_length",
    "petal width (cm)": "petal"
})
iris

     sepal_length  sepal_width  petal_length  petal    species
0             5.1          3.5           1.4    0.2     setosa
1             4.9          3.0           1.4    0.2     setosa
2             4.7          3.2           1.3    0.2     setosa
3             4.6          3.1           1.5    0.2     setosa
4             5.0          3.6           1.4    0.2     setosa
..            ...          ...           ...    ...        ...
145           6.7          3.0           5.2    2.3  virginica
146           6.3          2.5           5.0    1.9  virginica
147           6.5          3.0           5.2    2.0  virginica
148           6.2          3.4           5.4    2.3  virginica
149           5.9          3.0           5.1    1.8  virginica

[150 rows x 5 columns]

In [117]:
duckdb.sql("""
    SELECT
        species, 
        AVG(petal_length) AS avg_petal_length
    FROM iris
    GROUP BY species
    ORDER BY avg_petal_length DESC
""").df()

      species  avg_petal_length
0   virginica             5.552
1  versicolor             4.260
2      setosa             1.462

# Harjutused

In [125]:
def year_display(year: int) -> str:
    if year < 0:
        return f"{abs(year)} B.C."
    elif year > 0:
        return f"{year} A.D."
    else:
        return "Palju õnne, Jeesus!"

print(year_display(-10000))
print(year_display(2024))
print(year_display(0))

10000 B.C.
2024 A.D.
Palju õnne, Jeesus!

In [152]:
inimesed = ['Kati', 'Mari', 'Silver', 'Hannes']
numbrid = ['esimene', 'teine', 'kolmas', 'neljas']

jrk_nr = 0

for nimi in inimesed:
    nr = numbrid[jrk_nr].capitalize()
    if len(nimi) > 4:
        print(f"{nr} inimene kannab pikka nime: {nimi.upper()}")
    else:
        print(f"{nr} inimene kannab lühikest nime: {nimi}")
    # jrk_nr = jrk_nr + 1
    jrk_nr += 1

Esimene inimene kannab lühikest nime: Kati
Teine inimene kannab lühikest nime: Mari
Kolmas inimene kannab pikka nime: SILVER
Neljas inimene kannab pikka nime: HANNES